version: 2
sources:
  - name: raw
    schema: gz_raw_data
    tables:
      - name: sales
        identifier: raw_gz_sales  
        description: Data sales
        columns:
          - name: date_date
            description: the date of purchase
          - name: orders_id
            description: foreign key to ship
          - name: pot_id
            description: foreign key to product
          - name: revenue
            description: the amount paid by the customer to purchase the product. revenue = quantity * selling price
          - name: quantity
            description: the quantity of products purchased for this order
        tests:
          - unique:
              column_name: "(orders_id || '-' || pdt_id)"

      - name: product
        identifier: raw_gz_product
        description: products of Greenweez 
        columns:
          - name: products_id
            description: primary key of the table
            tests:
              - unique
              - not_null
          - name: purchase_price
            description: the purchase price of the product

      - name: ship
        identifier: raw_gz_ship 
        description: ship of Greenweez 
        columns:
          - name: orders_id
            description: primary key of the table
            tests:
              - unique
              - not_null
          - name: shipping_fee
            description: the price the customer pays for shipping
          - name: log_cost
            description: the cost of preparing the parcel in the warehouse 
          - name: ship_cost
            description: the shipping cost paid by Greenweez to the carrier/transporter
      - name: adwords
        identifier: raw_gz_adwords
      - name: bing
        identifier: raw_gz_bing
      - name: criteo
        identifier: raw_gz_criteo
      - name: facebook
        identifier: raw_gz_facebook
      - name: int_campaigns
        description: data from all campaigns
        tests:
          - unique:
              column_name: "(campaign_key || '-' || date_date)"
          - not_null:
              column_name:
                 - paid_source
                 - campaing_name

            


      





